server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /usuarios/ {
        proxy_pass http://host.docker.internal:3000/;
        proxy_set_header Host $host;
    }

    location /publicaciones/ {
        proxy_pass http://host.docker.internal:3000/;
        proxy_set_header Host $host;
    }

    location /comentarios/ {
        proxy_pass http://host.docker.internal:3000/;
        proxy_set_header Host $host;
    }

    location /reacciones/ {
        proxy_pass http://host.docker.internal:3000/;
        proxy_set_header Host $host;
    }
}
